My_CRUD_Project/My_CRUD_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('my_app.urls')),



]

My_CRUD_Project/my_app/urls.py
from django.conf.urls import url
from django.urls import path
from my_app import views

app_name = "my_app"

urlpatterns = [
path('',views.index,name="index"),
path('student_form/',views.student_form,name="student_form"),
path('department_form/',views.department_form,name="department_form"),
path('department_list/<int:s_id>/',views.department_list,name="department_list"),
path('edit_student/<int:s_id>/',views.edit_student,name="edit_student"),
path('edit_department/<int:department_id>/',views.edit_department,name ="edit_department"),
path('delete_department/<int:department_id>/',views.delete_department,name = "delete_department"),
path('delete_student/<int:student_id>/',views.delete_student,name="delete_student")


]

My_CRUD_Project/my_app/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    phone = models.CharField(max_length = 50)
    session = models.CharField(max_length = 50)
    blood_group = models.CharField(max_length = 50)
    religion = models.CharField(max_length = 50)
    nationality = models.CharField(max_length = 50)

    class Meta:
        db_table = "student"


    def __str__(self):
        return self.first_name + " " + self.last_name + " " + self.phone + " " + self.session +" " + self.blood_group + " " + self.religion + " " + self.nationality


class Department(models.Model):
    undergraduate = models.ForeignKey(Student, on_delete = models.CASCADE)
    dept_name = models.CharField(max_length = 50)
    establishing_date = models.DateField()
    rating = (
    (1,"Worst"),
    (2,"Bad"),
    (3,"Not_Bad"),
    (4,"Good"),
    (5,"Excellent!"),
    )
    num_stars = models.IntegerField(choices = rating)

    class Meta:
        db_table = "department"

    def __str__(self):
        return self.dept_name + " "  + " ,Rating "+ str(self.num_stars)

My_CRUD_Project/my_app/forms.py
from django import forms
from my_app import models

class StudentForm(forms.ModelForm):
    class Meta:
        model = models.Student
        fields="__all__"

class DepartmentForm(forms.ModelForm):
    establishing_date = forms.DateField(widget=forms.TextInput(attrs = {'type':'date'}))
    class Meta:
        model = models.Department
        fields = "__all__"

My_CRUD_Project/my_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from my_app.models import Student , Department
from my_app import forms
from django.db.models import Avg

# Create your views here.
def index(request):
    student_list = Student.objects.order_by('first_name')

    diction = {'title':"My CRUD Project",'student_list':student_list}
    return render(request,'my_app/index.html',context=diction)

def student_form(request):
    form = forms.StudentForm()
    if request.method == 'POST':
        form = forms.StudentForm(request.POST)
        if form.is_valid():
            form.save(commit = True)
            return index(request)




    diction = {'title':"Add Student",'student_form': form}
    return render(request,'my_app/student_form.html',context=diction)

def department_form(request):
    form = forms.DepartmentForm()
    if request.method == 'POST':
        form = forms.DepartmentForm(request.POST)
        if form.is_valid():
            form.save(commit = True)
            return index(request)
    diction = {'title':" Add Department",'department_form':form}
    return render(request,'my_app/department_form.html',context=diction)

def department_list(request,s_id):
    student_info = Student.objects.get(pk = s_id)
    department_list = Department.objects.filter(undergraduate = s_id).order_by('dept_name','establishing_date')
    department_rating = Department.objects.filter(undergraduate = s_id).aggregate(Avg('num_stars'))
    diction = {'title':"Department List ",'student_info':student_info,'department_list':department_list,'department_rating':department_rating}
    return render(request,'my_app/department_list.html',context=diction)

def edit_student(request,s_id):
    student_info = Student.objects.get(pk = s_id)
    form = forms.StudentForm(instance = student_info)
    if request.method == 'POST':
        form = forms.StudentForm(request.POST,instance = student_info)
        if form.is_valid():
            form.save(commit = True)
            return department_list(request,s_id)
    diction ={'edit_form': form}
    return render(request,'my_app/edit_student.html',context = diction)



def edit_department(request,department_id):
    department_info = Department.objects.get(pk = department_id)
    form = forms.DepartmentForm(instance = department_info)
    diction ={}
    if request.method == 'POST':
        form = forms.DepartmentForm(request.POST,instance=department_info)
        if form.is_valid():
            form.save(commit = True)
            diction.update({'success_text':"Successfully Update!"})
    diction.update({'title': "Edit Department" ,'edit_form':form})
    diction.update({'department_id':department_id})
    return render(request,'my_app/edit_department.html',context = diction)


def delete_department(request,department_id):
    department = Department.objects.get(pk = department_id).delete()
    diction = {"delete_success": "Department Deleted Successfully !"}
    return render(request, 'my_app/delete.html',context = diction)

def delete_student(request,student_id):
    student = Student.objects.get(pk = student_id).delete()
    diction = {'delete_success':"Delete Student Successfully !"}
    return render(request,'my_app/delete.html',context=diction)

My_CRUD_Project/templates/my_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'my_app:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'my_app:student_form' %}">Add Student</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'my_app:department_form' %}">Add Department</a>
        </li>



      </ul>
    </div>
  </div>
</nav>

<div class="container" >
  {% block body_block %}


  {% endblock %}

</div>



  </body>
</html>

My_CRUD_Project/templates/my_app/delete.html
{% extends 'my_app/base.html' %}
{% block body_block %}
<div class="alert alert-danger">
  {{ delete_success }}
</div>
{% endblock %}

My_CRUD_Project/templates/my_app/department_form.html
{% extends 'my_app/base.html' %}
{% block body_block %}
{{title}}
<form  method="POST">
  {{ department_form.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="submit" class="btn btn-primary">

</form>
{% endblock %}

My_CRUD_Project/templates/my_app/department_list.html
{% extends 'my_app/base.html' %}
{% block body_block %}
{{title}}
<h4>Studnt Name : {{student_info.first_name}} {{student_info.last_name}}</h4>
<h4>Phone : {{ student_info.phone }}</h4>
<h4>Session : {{ student_info.session}}</h4>
<h4>Blood Group : {{ student_info.blood_group}}</h4>
<h4>Religion : {{ student_info.religion }}</h4>
<h4>Nationality : {{ student_info.nationality }}</h4>
<h4>Department Rating : {{ department_rating.num_stars__avg }}</h4>

<h3>List of Department</h3>
<a href="{% url 'my_app:edit_student' s_id=student_info.id %}" class="btn btn-primary">Edit</a>

<table class="table table-bordered">
  <tr>
    <th>Department Name</th>
    <th>Establishing Date</th>
    <th>Rating</th>
  </tr>
  {% for department_list in department_list %}
  <tr>
    <td><a href="{% url 'my_app:edit_department' department_id=department_list.id %}">{{ department_list.dept_name}}</a></td>
    <td>{{ department_list.establishing_date|date:"M d,Y"}}</td>
    <td>{{ department_list.num_stars}}</td>
  </tr>
  {% endfor %}

</table>

<br>
<a href="{% url 'my_app:delete_student' student_id=student_info.id %}" class="btn btn-danger btn-sm" onclick="return confirm('Delete Student?')">Delete</a>





{% endblock %}

My_CRUD_Project/templates/my_app/edit_department.html
{% extends 'my_app/base.html' %}
{% block body_block %}
<h4>{{ title}}</h4>

{% if success_text %}
<div class="alert alert-success">
  {{ success_text }}
</div>
{% endif %}
<form  method="POST">
  {{ edit_form.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="Update" class="btn btn-primary">
</form>
<br>

<a href="{% url 'my_app:delete_department' department_id=department_id %}" class='btn btn-danger btn-sm' onclick="return confirm('Delete This Form !')">Delete</a>

{% endblock %}

My_CRUD_Project/templates/my_app/edit_student.html
{% extends 'my_app/base.html' %}
{% block body_block %}
<h4>Edit Student</h4>
<form  method="POST">
  {{ edit_form.as_p }}
  {% csrf_token %}

  <input type="submit" name="submit" value="Update" class = "btn btn-info btn-sm">
</form>
{% endblock %}

My_CRUD_Project/templates/my_app/index.html
{% extends 'my_app/base.html' %}
{% block body_block %}
{{title}}
<h4>List of Student</h4>
<ul>
  {% if student_list %}
  {% for student in student_list %}
      <li><a href="{% url 'my_app:department_list' s_id=student.id %}">{{ student.first_name }} {{student.last_name}}</a></li>
  {% endfor %}
  {% else %}
  <h4>No student in the list</h4>

  {% endif %}

</ul>


{% endblock %}

My_CRUD_Project/templates/my_app/student_form.html
{% extends 'my_app/base.html' %}
{% block body_block %}
{{title}}
<form  method="POST">
  {{ student_form.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="submit" class="btn btn-primary">

</form>
{% endblock %}